name: tf-prob
dependencies:
  - python=3.6
  - jupyter
  - jupyterlab
  - pandas
  - matplotlib
  - seaborn
  - tensorflow-gpu==1.13.1
  - nb_conda
  - networkx
  - numexpr
  - numpy==1.15.0
  - matplotlib==2.2.2
  - scikit-learn
