name: tf-prob
dependencies:
  - jupyter
  - jupyterlab
  - pandas
  - matplotlib
  - seaborn
  - nb_conda
  - networkx
  - numexpr
  - numpy
  - matplotlib
  - scikit-learn
  - tensorflow-gpu==2.0.0
  - tensorflow-probability==0.8.0
